### ISSUE TITLE
1.12.2 null pointer on getMinecraftProfile

### ISSUE THREAD

**Issue by Dylan-Filbert** [Sintinium/oauth#35] opened 2022-05-09 01:11 UTC
I'm on a mac, running 1.12.2, i'm using the 1.06.4 jar which the site i got it from said was compatible, https://www.curseforge.com/minecraft/mc-mods/oauth/files this thing, but now i have this error
<img width="825" alt="Screen Shot 2022-05-09 at 08 01 12" src="https://user-images.githubusercontent.com/105181343/167324481-bb2fe495-5f1b-4caa-aa6b-1be02ca5bb88.png">

can you help, i'm just trying to play some pixelmon with my friends

**Comment by Dylan-Filbert** [comment] 2022-05-09 01:15
Oh yeah the forge version is the 1.12.2 one that ends in a 60 i believe, its the latest one, i probably shouldve mentioned that in the first post sorry

**Comment by Sintinium** [comment] 2022-12-10 15:51
I believe this is a duplicate of #20

**Closed as not planned by Sintinium** 2022-12-10 15:51 UTC
