### ISSUE TITLE
Got this and it told me to post it here.

### ISSUE THREAD

**Issue by Splattter** [Sintinium/oauth#57] opened 2023-05-20 20:57 UTC
[2023-05-20-2.log.gz](https://github.com/Sintinium/oauth/files/11523200/2023-05-20-2.log.gz)
![image](https://github.com/Sintinium/oauth/assets/134171053/9ae0880d-6967-4bf8-8842-173926fed2e9)

I don't know what's wrong..

**Comment by Sintinium** [comment] 2023-05-21 01:14
Thanks, I haven't had the time to fix the old 1.12 version but it's a known bug and a duplicate of #52

**Closed as completed by Sintinium** 2023-05-21 01:14 UTC
