### ISSUE TITLE
Cannot log in with a microsoft account on 1.12.2 version 1.06.4

### ISSUE THREAD

**Issue by samche2000** [Sintinium/oauth#43] opened 2022-07-30 10:00 UTC
Hello,

The account is a chlidren account that i can manage cause i'm the father. Children accounts have limitations, maybe it's a way to investigate. This account was created yesterday so it was never use on other platforms.

In red, the account is offline in Minecraft servers page. When trying to log in, everything is well in browser. No errors appeared on the screen but the account is always offline in Minecraft servers page. I can't login on servers caus "login failed : null".
[latest.oauth.1.06.4.log](https://github.com/Sintinium/oauth/files/9225922/latest.oauth.1.06.4.log)

If you need more tests, i'm free for you

**Comment by xJon** [comment] 2022-08-13 00:18
Also experiencing this issue.

**Comment by Sintinium** [comment] 2022-11-10 15:43
duplicate of #44

**Closed as completed by Sintinium** 2022-11-10 15:43 UTC
