### ISSUE TITLE
Failed to login to Microsoft Account (1.16.5)

### ISSUE THREAD

**Issue by SpokenWig620933** [Sintinium/oauth#17] opened 2022-01-22 02:02 UTC
`[21:00:31] [Oauth microsoft/INFO]: [com.sintinium.oauth.gui.ErrorScreen:<init>:31]: java.lang.NullPointerException
[21:00:31] [Oauth microsoft/INFO]: [com.sintinium.oauth.gui.ErrorScreen:<init>:31]: 	at com.sintinium.oauth.login.MicrosoftLogin.getXstsToken(MicrosoftLogin.java:285)
[21:00:31] [Oauth microsoft/INFO]: [com.sintinium.oauth.gui.ErrorScreen:<init>:31]: 	at com.sintinium.oauth.login.MicrosoftLogin$$Lambda$25161/1250740839.apply(Unknown Source)
[21:00:31] [Oauth microsoft/INFO]: [com.sintinium.oauth.gui.ErrorScreen:<init>:31]: 	at com.sintinium.oauth.login.MicrosoftLogin.callIfNotCancelled(MicrosoftLogin.java:155)
[21:00:31] [Oauth microsoft/INFO]: [com.sintinium.oauth.gui.ErrorScreen:<init>:31]: 	at com.sintinium.oauth.login.MicrosoftLogin.loginWithToken(MicrosoftLogin.java:122)
[21:00:31] [Oauth microsoft/INFO]: [com.sintinium.oauth.gui.ErrorScreen:<init>:31]: 	at com.sintinium.oauth.login.MicrosoftLogin.login(MicrosoftLogin.java:103)
[21:00:31] [Oauth microsoft/INFO]: [com.sintinium.oauth.gui.ErrorScreen:<init>:31]: 	at com.sintinium.oauth.gui.profile.ProfileSelectionScreen.lambda$onMicrosoftType$10(ProfileSelectionScreen.java:224)
[21:00:31] [Oauth microsoft/INFO]: [com.sintinium.oauth.gui.ErrorScreen:<init>:31]: 	at com.sintinium.oauth.gui.profile.ProfileSelectionScreen$$Lambda$25154/1999980021.run(Unknown Source)
[21:00:31] [Oauth microsoft/INFO]: [com.sintinium.oauth.gui.ErrorScreen:<init>:31]: 	at java.lang.Thread.run(Thread.java:745)
[21:00:31] [Oauth microsoft/INFO]: [com.sintinium.oauth.gui.profile.ProfileSelectionScreen:lambda$onMicrosoftType$10:227]: java.lang.NullPointerException
[21:00:31] [Oauth microsoft/INFO]: [com.sintinium.oauth.gui.profile.ProfileSelectionScreen:lambda$onMicrosoftType$10:227]: 	at com.sintinium.oauth.login.MicrosoftLogin.getXstsToken(MicrosoftLogin.java:285)
[21:00:31] [Oauth microsoft/INFO]: [com.sintinium.oauth.gui.profile.ProfileSelectionScreen:lambda$onMicrosoftType$10:227]: 	at com.sintinium.oauth.login.MicrosoftLogin$$Lambda$25161/1250740839.apply(Unknown Source)
[21:00:31] [Oauth microsoft/INFO]: [com.sintinium.oauth.gui.profile.ProfileSelectionScreen:lambda$onMicrosoftType$10:227]: 	at com.sintinium.oauth.login.MicrosoftLogin.callIfNotCancelled(MicrosoftLogin.java:155)
[21:00:31] [Oauth microsoft/INFO]: [com.sintinium.oauth.gui.profile.ProfileSelectionScreen:lambda$onMicrosoftType$10:227]: 	at com.sintinium.oauth.login.MicrosoftLogin.loginWithToken(MicrosoftLogin.java:122)
[21:00:31] [Oauth microsoft/INFO]: [com.sintinium.oauth.gui.profile.ProfileSelectionScreen:lambda$onMicrosoftType$10:227]: 	at com.sintinium.oauth.login.MicrosoftLogin.login(MicrosoftLogin.java:103)
[21:00:31] [Oauth microsoft/INFO]: [com.sintinium.oauth.gui.profile.ProfileSelectionScreen:lambda$onMicrosoftType$10:227]: 	at com.sintinium.oauth.gui.profile.ProfileSelectionScreen.lambda$onMicrosoftType$10(ProfileSelectionScreen.java:224)
[21:00:31] [Oauth microsoft/INFO]: [com.sintinium.oauth.gui.profile.ProfileSelectionScreen:lambda$onMicrosoftType$10:227]: 	at com.sintinium.oauth.gui.profile.ProfileSelectionScreen$$Lambda$25154/1999980021.run(Unknown Source)
[21:00:31] [Oauth microsoft/INFO]: [com.sintinium.oauth.gui.profile.ProfileSelectionScreen:lambda$onMicrosoftType$10:227]: 	at java.lang.Thread.run(Thread.java:745)
`

**Comment by SpokenWig620933** [comment] 2022-01-22 02:02
That's the entire error from this mod, and it's just my 1 account for some reason, my other 2 work just fine.

**Comment by Sintinium** [comment] 2022-01-22 06:17
You're not the only one with issues a lot of reported an issue today. I'll try to have a fix out asap. Thanks for the report

**Comment by Sintinium** [comment] 2022-01-22 14:10
So after some testing and looking at https://downdetector.com/status/minecraft/ it seems there was a server issue around the time you posted. Is it still happening? Because I can't reproduce it

**Comment by SpokenWig620933** [comment] 2022-01-22 18:07
It is still happening, as I stated though it seems to be the one account out of my 3 which all have bought minecraft and were all migrated.

**Comment by SpokenWig620933** [comment] 2022-01-22 18:08
I don't understand what is happening, and the account works just fine if I load the game from the launcher, but I can't add the account to OAuth's list

**Comment by Sintinium** [comment] 2022-01-22 19:55
Could you try updating to the latest version (1.1.9) I just uploaded onto curseforge. It most likely won't fix the issue but it'll provide a better log file. If you still get the issue on that version could you give me the new log? Thanks!

**Comment by SpokenWig620933** [comment] 2022-01-22 20:07
`[15:05:50] [Oauth status/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[15:05:50] [Oauth status/INFO]: Environment: PROD
[15:06:02] [Oauth microsoft/INFO]: [com.sintinium.oauth.gui.ErrorScreen:<init>:31]: java.lang.IllegalStateException: Missing token from responseJson.has("Token")
[15:06:02] [Oauth microsoft/INFO]: [com.sintinium.oauth.gui.ErrorScreen:<init>:31]: 	at com.sintinium.oauth.login.MicrosoftLogin.getXstsToken(MicrosoftLogin.java:367)
[15:06:02] [Oauth microsoft/INFO]: [com.sintinium.oauth.gui.ErrorScreen:<init>:31]: 	at com.sintinium.oauth.login.MicrosoftLogin$$Lambda$22369/1360837305.apply(Unknown Source)
[15:06:02] [Oauth microsoft/INFO]: [com.sintinium.oauth.gui.ErrorScreen:<init>:31]: 	at com.sintinium.oauth.login.MicrosoftLogin.callIfNotCancelled(MicrosoftLogin.java:157)
[15:06:02] [Oauth microsoft/INFO]: [com.sintinium.oauth.gui.ErrorScreen:<init>:31]: 	at com.sintinium.oauth.login.MicrosoftLogin.loginWithToken(MicrosoftLogin.java:124)
[15:06:02] [Oauth microsoft/INFO]: [com.sintinium.oauth.gui.ErrorScreen:<init>:31]: 	at com.sintinium.oauth.login.MicrosoftLogin.login(MicrosoftLogin.java:105)
[15:06:02] [Oauth microsoft/INFO]: [com.sintinium.oauth.gui.ErrorScreen:<init>:31]: 	at com.sintinium.oauth.gui.profile.ProfileSelectionScreen.lambda$onMicrosoftType$10(ProfileSelectionScreen.java:224)
[15:06:02] [Oauth microsoft/INFO]: [com.sintinium.oauth.gui.ErrorScreen:<init>:31]: 	at com.sintinium.oauth.gui.profile.ProfileSelectionScreen$$Lambda$22362/1501302557.run(Unknown Source)
[15:06:02] [Oauth microsoft/INFO]: [com.sintinium.oauth.gui.ErrorScreen:<init>:31]: 	at java.lang.Thread.run(Thread.java:745)
[15:06:02] [Oauth microsoft/INFO]: [com.sintinium.oauth.gui.profile.ProfileSelectionScreen:lambda$onMicrosoftType$10:227]: java.lang.IllegalStateException: Missing token from responseJson.has("Token")
[15:06:02] [Oauth microsoft/INFO]: [com.sintinium.oauth.gui.profile.ProfileSelectionScreen:lambda$onMicrosoftType$10:227]: 	at com.sintinium.oauth.login.MicrosoftLogin.getXstsToken(MicrosoftLogin.java:367)
[15:06:02] [Oauth microsoft/INFO]: [com.sintinium.oauth.gui.profile.ProfileSelectionScreen:lambda$onMicrosoftType$10:227]: 	at com.sintinium.oauth.login.MicrosoftLogin$$Lambda$22369/1360837305.apply(Unknown Source)
[15:06:02] [Oauth microsoft/INFO]: [com.sintinium.oauth.gui.profile.ProfileSelectionScreen:lambda$onMicrosoftType$10:227]: 	at com.sintinium.oauth.login.MicrosoftLogin.callIfNotCancelled(MicrosoftLogin.java:157)
[15:06:02] [Oauth microsoft/INFO]: [com.sintinium.oauth.gui.profile.ProfileSelectionScreen:lambda$onMicrosoftType$10:227]: 	at com.sintinium.oauth.login.MicrosoftLogin.loginWithToken(MicrosoftLogin.java:124)
[15:06:02] [Oauth microsoft/INFO]: [com.sintinium.oauth.gui.profile.ProfileSelectionScreen:lambda$onMicrosoftType$10:227]: 	at com.sintinium.oauth.login.MicrosoftLogin.login(MicrosoftLogin.java:105)
[15:06:02] [Oauth microsoft/INFO]: [com.sintinium.oauth.gui.profile.ProfileSelectionScreen:lambda$onMicrosoftType$10:227]: 	at com.sintinium.oauth.gui.profile.ProfileSelectionScreen.lambda$onMicrosoftType$10(ProfileSelectionScreen.java:224)
[15:06:02] [Oauth microsoft/INFO]: [com.sintinium.oauth.gui.profile.ProfileSelectionScreen:lambda$onMicrosoftType$10:227]: 	at com.sintinium.oauth.gui.profile.ProfileSelectionScreen$$Lambda$22362/1501302557.run(Unknown Source)
[15:06:02] [Oauth microsoft/INFO]: [com.sintinium.oauth.gui.profile.ProfileSelectionScreen:lambda$onMicrosoftType$10:227]: 	at java.lang.Thread.run(Thread.java:745)`

Just loaded my pack and tried it on that account again for this to appear.

**Comment by Sintinium** [comment] 2022-01-23 06:46
Is the date of birth on the account under 18? After looking through the api I think that could be an issue

**Comment by SpokenWig620933** [comment] 2022-01-23 06:51
It appears so

**Comment by Sintinium** [comment] 2022-01-23 07:02
Alright I think it might take some time after changing the age/using the family account system to add permission. I'll be sure to add a proper error screen for this issue. If you have any questions or need help let me know

**Closed as completed by Sintinium** 2022-01-23 07:02 UTC
Labels: can't reproduce

**Comment by SpokenWig620933** [comment] 2022-01-23 23:46
Thank you, this fixed the issue! I'd recommend noting this in the plugin's description on the page so people know before downloading this as well.
